name    : resuable workflow
on      : 
     workflow_call:
      inputs :
        artifact-name:
            description : The name of deployable artifact file
            required    : false
            default     : dist
            type        : string
jobs    :
  deploy:
    runs-on : ubuntu-latest
    steps   :
      - name : Get code
        uses : actions/download-artifact@v4
        with :
          name : ${{inputs.artifact-name}}
      - name : outputing the files
        run  : ls
      - name : outputing information
        run  : echo "Deploying and uploading ..."