name    : resuable workflow
on      : 
     workflow_call
jobs    :
  deploy:
    runs-on : ubunut-latest
    steps   :
      - name : outputing information
        run  : echo "Deploying and uploading ..."